name = "pakdebateforumn-worker"
main = "src/index.mjs"

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

[assets]
directory = "./public"

[env.production]
routes = [
  { pattern = "pakdebateforum.com/*", zone_name = "pakdebateforum.com" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "pakdebate_d1"
database_id = "14008724-ead1-4f68-a585-0025435e4c3d"
